export const tarotCards = [
  { id: "001", name: "The Fool", meaning: "New beginnings, optimism, trust in life", reversedMeaning: "Recklessness, taken advantage of, inconsideration" },
  { id: "002", name: "The Magician", meaning: "Action, the power to manifest", reversedMeaning: "Manipulation, poor planning, untapped talents" },
  { id: "003", name: "The High Priestess", meaning: "Inaction, going within, the subconscious", reversedMeaning: "Secrets, disconnected from intuition, withdrawal" },
  { id: "004", name: "The Empress", meaning: "Abundance, nurturing, fertility, life in bloom!", reversedMeaning: "Dependence, smothering, emptiness, nosiness" },
  { id: "005", name: "The Emperor", meaning: "Structure, stability, rules and power", reversedMeaning: "Tyranny, rigidity, coldness" },
  { id: "006", name: "The Hierophant", meaning: "Institutions, tradition, society and its rules", reversedMeaning: "Rebellion, subversiveness, new approaches" },
  { id: "007", name: "The Lovers", meaning: "Sexuality, passion, choice, uniting", reversedMeaning: "Loss of balance, one-sidedness, disharmony" },
  { id: "008", name: "The Chariot", meaning: "Movement, progress, integration", reversedMeaning: "Lack of control, lack of direction, aggression" },
  { id: "009", name: "Strength", meaning: "Courage, subtle power, integration of animal self", reversedMeaning: "Self-doubt, weakness, insecurity" },
  { id: "010", name: "The Hermit", meaning: "Meditation, solitude, consciousness", reversedMeaning: "Isolation, loneliness, withdrawal" },
  { id: "011", name: "Wheel of Fortune", meaning: "Cycles, change, ups and downs", reversedMeaning: "Bad luck, resistance to change, breaking cycles" },
  { id: "012", name: "Justice", meaning: "Fairness, equality, balance", reversedMeaning: "Dishonesty, unaccountability, unfairness" },
  { id: "013", name: "The Hanged Man", meaning: "Surrender, new perspective, enlightenment", reversedMeaning: "Stalling, needless sacrifice, fear of sacrifice" },
  { id: "014", name: "Death", meaning: "End of cycle, beginnings, change, metamorphosis", reversedMeaning: "Fear of change, holding on, stagnation, decay" },
  { id: "015", name: "Temperance", meaning: "Middle path, patience, finding meaning", reversedMeaning: "Extremes, excess, lack of balance" },
  { id: "016", name: "The Devil", meaning: "Bondage, materialism, playfulness", reversedMeaning: "Freedom, release, restoring control" },
  { id: "017", name: "The Tower", meaning: "Sudden upheaval, pride, disaster", reversedMeaning: "Disaster avoided, delayed disaster, fear of suffering" },
  { id: "018", name: "The Star", meaning: "Hope, calm, a good omen!", reversedMeaning: "Insecurity, discouragement, faithlessness" },
  { id: "019", name: "The Moon", meaning: "Mystery, the subconscious, dreams", reversedMeaning: "Confusion, fear, misinterpretation" },
  { id: "020", name: "The Sun", meaning: "Success, happiness, all will be well", reversedMeaning: "Negativity, depression, sadness" },
  { id: "021", name: "Judgement", meaning: "Reflection, reckoning, awakening", reversedMeaning: "Lack of self-awareness, doubt, self-loathing" },
  { id: "022", name: "The World", meaning: "Fulfillment, harmony, completion", reversedMeaning: "Incompletion, no closure, incomplete goals" },
  // Add more cards as needed
];